export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SAGA = "LOGIN_USER_SAGA";
export const SIGNUP_USER_SAGA = "SIGNUP_USER_SAGA";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SAGA = "LOGOUT_USER_SAGA";

export const CLEAR_TOAST = "CLEAR_TOAST";
export const SET_TOAST = "SET_TOAST";

export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
export const SET_SIGNUP_STATUS = "SET_SIGNUP_STATUS";
export const SET_LIKE_STATUS = "SET_LIKE_STATUS";
export const SET_COMMENT_STATUS = "SET_COMMENT_STATUS";
export const SET_POSTS_STATUS = "SET_POSTS_STATUS";
export const SET_POST_STATUS = "SET_POST_STATUS";
export const SET_PROFILE_STATUS = "SET_PROFILE_STATUS";
