export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SAGA = "LOGIN_USER_SAGA";
export const SIGNUP_USER_SAGA = "SIGNUP_USER_SAGA";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SAGA = "LOGOUT_USER_SAGA";

export const CLEAR_TOAST = "CLEAR_TOAST";
export const SET_TOAST = "SET_TOAST";

export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
export const SET_SIGNUP_STATUS = "SET_SIGNUP_STATUS";
export const SET_LIKE_STATUS = "SET_LIKE_STATUS";
export const SET_COMMENT_STATUS = "SET_COMMENT_STATUS";
export const SET_POSTS_STATUS = "SET_POSTS_STATUS";
export const SET_POST_STATUS = "SET_POST_STATUS";
export const SET_PROFILE_STATUS = "SET_PROFILE_STATUS";

export const SET_POSTS = "SET_POSTS";
export const CREATE_POST = "CREATE_POST";
export const DELETE_POST = "DELETE_POST";
export const SET_FOLLOWINGS_POSTS = "SET_FOLLOWINGS_POSTS";
export const LIKE_POST = "LIKE_POST";
export const UNLIKE_POST = "UNLIKE_POST";

export const SET_POSTS_SAGA = "SET_POSTS_SAGA";
export const CREATE_POST_SAGA = "CREATE_POST_SAGA";
export const DELETE_POST_SAGA = "DELETE_POST_SAGA";
export const SET_FOLLOWINGS_POSTS_SAGA = "SET_FOLLOWINGS_POSTS_SAGA";
export const LIKE_POST_SAGA = "LIKE_POST_SAGA";
export const UNLIKE_POST_SAGA = "UNLIKE_POST_SAGA";
